name: Java CI to create and upload release on pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package
      - run: mkdir staging && mv app/target/*jar-with-dependencies.jar staging/pvis.jar
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging/pvis${{ github.run_number }}.jar
          retention-days: 1
      - uses: ncipollo/release-action@v1
        with:
          name: Portfolio Visualizer
          tag: some-tag
          artifacts: staging/pvis${{ github.run_number }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}

