name: Create realse jar
on:
  pull_request:
    branches: [ "release" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package
      - run: mkdir staging && mv app/target/*jar-with-dependencies.jar staging/pvis-v${{ github.run_number }}.jar
      - name: Upload jar
        uses: ncipollo/release-action@v1
        with:
          name: Portfolio Visualizer
          tag: v${{ github.run_number }}
          artifacts: staging/pvis-v${{ github.run_number }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}

